Update patch set 3
Patch Set 3:

> Change has been successfully cherry-picked as b99106a7a54846622f378852f349a124ecf7d18f by Adam Langley

I'll comment here instead of creating another issue. bin/bio_test.exe still fails on Windows due to a missing WSAStartup(). Result:

crypto/bio/bio_test.cc(78): error: Expected: (-1) != (listening_sock), actual: -1 vs -1
10093

Patch-set: 3
CC: Gerrit User 5480 <5480@66b711a4-aa9b-3dac-9062-916540830212>