Fixes error when declaring ssize_t in digest.cc and transport_common.cc
Added a namespace 'boringssl' to the `typedef int ssize_t;` to prevent conflicts with the same type being declared in MinGW64 (mingw64/x86_64-w64-mingw32/include/corecrt.h)

Before this fix, the following error would get thrown when compiling with MinGW64:
error: conflicting declaration 'typedef int ssize_t'
   42 | typedef int ssize_t;
      |             ^~~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h:10,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/stddef.h:7,
                 from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/9.3.0/include/stddef.h:1,
                 from D:/Code/Misc/C++/Projects/boringssl/src/include/openssl/base.h:59,
                 from D:\Code\Misc\C++\Projects\boringssl\src\tool\digest.cc:15:
C:/msys64/mingw64/x86_64-w64-mingw32/include/corecrt.h:50:35: note: previous declaration as 'typedef long long int ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~

Change-Id: I6cf8f7357591372cb842c8b6b769173693e74449