Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> This breaks libfuzzer builds in oss-fuzz:
> 
> + clang++ -g -fsanitize=address -fsanitize-coverage=edge,indirect-calls,8bit-counters -stdlib=libc++ -DBORINGSSL_UNSAFE_FUZZER_MODE -Wl,-whole-archive /usr/local/lib/libc++.a /usr/local/lib/libc++abi.a -Wl,-no-whole-archive -std=c++11 -o /out/client -lfuzzer /src/boringssl/fuzz/client.cc -I /src/boringssl/include ./ssl/libssl.a ./crypto/libcrypto.a
> /src/boringssl/fuzz/client.cc:262:3: error: use of undeclared identifier 'RAND_reset_for_fuzzing'
>   RAND_reset_for_fuzzing();
>   ^
> 
> 
> Should we change the way we compile fuzzers?

Oh, I didn't realize you all weren't just using the CMake build. You'd need to add -DBORINGSSL_UNSAFE_DETERMINISTIC_MODE too, but that's actually kinda annoying. How about I tweak base.h so that UNSAFE_FUZZER_MODE implies UNSAFE_DETERMINISTIC_MODE. Then I don't break existing build setups.

Patch-set: 4