[build] Fix build with HEAD clang.
The HEAD version of Clang fails to build boringssl due to the following
warning triggered at -Werror:

    /usr/local/google/home/dthorn/curl/boringssl/tool/digest.cc:229:12:
    error: variable 'bad_hash_lines' set but not used

This change removes the variable.

Change-Id: I25009925d9a2dfc5b1783accab19e4b861db4ec2