Update patch set 2
Patch Set 2:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 30724: Change could not be merged due to a path conflict. Please rebase the change locally and upload the rebased commit for review.

Patch-set: 2
Tag: autogenerated:cq:full-run
Reviewer: Gerrit User 6985 <6985@66b711a4-aa9b-3dac-9062-916540830212>