Update patch set 1
Patch Set 1:

I cannot push my changes to the master-with-bazel repository anymore:
```
To https://boringssl.googlesource.com/boringssl
 ! [remote rejected]     master-with-bazel -> master-with-bazel (prohibited by Gerrit: not permitted: update)
error: failed to push some refs to 'https://boringssl.googlesource.com/boringssl'
```

I will try to fix the code in the master branch and push it there, but they look pretty different, and I do not really know how they relate.

I'll give it a try...

Patch-set: 1