Bring ERR_ERROR_STRING_BUF_LEN up to 256
The commit 23d6e4cce97a ("Replace BIO_snprintf with snprintf within the library")
make GCC (gcc 9.4.0, ubuntu 20.04) warning, and build failed:

[88/162] Building C object crypto/CMakeFiles/crypto.dir/err/err.c.o
FAILED: crypto/CMakeFiles/crypto.dir/err/err.c.o
/usr/bin/cc -DBORINGSSL_IMPLEMENTATION -I/root/projects/boringssl/include -Werror -Wformat=2 -Wsign-compare -Wwrite-strings -Wvla -Wshadow -Wtype-limits -ggdb -Wall -fvisibility=hidden -fno-common -Wno-free-nonheap-object -Wimplicit-fallthrough -Wformat-signedness -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -D_XOPEN_SOURCE=700 -O3 -DNDEBUG -std=gnu11 -MD -MT crypto/CMakeFiles/crypto.dir/err/err.c.o -MF crypto/CMakeFiles/crypto.dir/err/err.c.o.d -o crypto/CMakeFiles/crypto.dir/err/err.c.o -c /root/projects/boringssl/crypto/err/err.c
/root/projects/boringssl/crypto/err/err.c: In function ‘ERR_error_string’:
/root/projects/boringssl/crypto/err/err.c:569:22: error: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size between 24 and 87 [-Werror=format-truncation=]
  569 |   snprintf(buf, len, "error:%08" PRIx32 ":%s:OPENSSL_internal:%s", packed_error,
      |                      ^~~~~~~~~~~
/root/projects/boringssl/crypto/err/err.c:569:63: note: format string is defined here
  569 |   snprintf(buf, len, "error:%08" PRIx32 ":%s:OPENSSL_internal:%s", packed_error,
      |                                                               ^~
In file included from /usr/include/stdio.h:867,
                 from /root/projects/boringssl/include/openssl/err.h:112,
                 from /root/projects/boringssl/crypto/err/err.c:111:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 34 and 160 bytes into a destination of size 120
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/projects/boringssl/crypto/err/err.c: In function ‘ERR_print_errors_cb’:
/root/projects/boringssl/crypto/err/err.c:569:22: error: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size between 24 and 87 [-Werror=format-truncation=]
  569 |   snprintf(buf, len, "error:%08" PRIx32 ":%s:OPENSSL_internal:%s", packed_error,
      |                      ^~~~~~~~~~~
/root/projects/boringssl/crypto/err/err.c:569:63: note: format string is defined here
  569 |   snprintf(buf, len, "error:%08" PRIx32 ":%s:OPENSSL_internal:%s", packed_error,
      |                                                               ^~
In file included from /usr/include/stdio.h:867,
                 from /root/projects/boringssl/include/openssl/err.h:112,
                 from /root/projects/boringssl/crypto/err/err.c:111:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 34 and 160 bytes into a destination of size 120
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[149/162] Building CXX object ssl/test/CMakeFiles/bssl_shim.dir/test_config.cc.o
ninja: build stopped: subcommand failed.

Since the openssl has fixed the concern in commmit ebd87230ac96 ("Bring
ERR_ERROR_STRING_BUF_LEN down to 120.") on Feb 6, 2016:

RT2890: Wrong size in ERR_string_error description.
https://github.com/openssl/openssl/commit/a0474357743b5cc4db1b5428ac3db85b1168d3a9

Bring up to 256 now, to fix the build failure on GCC, and align to the
openssl documentation 'buf must be at least 256 bytes long':
https://github.com/openssl/openssl/blob/master/doc/man3/ERR_error_string.pod

Change-Id: Ia6f90b4af0f003068a42444d37e00ba777d64a04
Signed-off-by: Haiyue Wang <haiyue.wang@intel.com>