Update patch set 6
Patch Set 6:

> utf-8 swich partially works. there is one error.
> 
> error message is here (build using ninja, vs2017)
> 
> [1/2] Building CXX object decrepit\CMakeFiles\decrepit_test.dir\ripemd\ripemd_test.cc.obj
> FAILED: decrepit/CMakeFiles/decrepit_test.dir/ripemd/ripemd_test.cc.obj 
> C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1413~1.261\bin\Hostx64\x64\cl.exe  /nologo /TP -DBORINGSSL_IMPLEMENTATION -DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_STL_EXTRA_DISABLED_WARNINGS="4774 4987" -I..\third_party\googletest\include -I..\decrepit\..\include -utf-8 -Wall -WX  -wd4061 -wd4100 -wd4127 -wd4200 -wd4204 -wd4221 -wd4242 -wd4244 -wd4267 -wd4371 -wd4388 -wd4296 -wd4350 -wd4365 -wd4389 -wd4464 -wd4510 -wd4512 -wd4514 -wd4548 -wd4610 -wd4623 -wd4625 -wd4626 -wd4668 -wd4706 -wd4710 -wd4711 -wd4800 -wd4820 -wd5026 -wd5027  -w44265 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Fodecrepit\CMakeFiles\decrepit_test.dir\ripemd\ripemd_test.cc.obj /Fddecrepit\CMakeFiles\decrepit_test.dir\ /FS -c ..\decrepit\ripemd\ripemd_test.cc
> ..\decrepit\ripemd\ripemd_test.cc(112): error C2220: warning treated as error - no 'object' file generated
> ..\decrepit\ripemd\ripemd_test.cc(112): warning C4819: The file contains a character that cannot be represented in the current code page (0). Save the file in Unicode format to prevent data loss
> ninja: build stopped: subcommand failed.
> 
> ripemd_test.cc(line:112) 
> has utf-8 left/right double quotation mark on string literal like below.
> 
>   fprintf(stderr, "Digest incorrect for “million a's” test: ");
> 
> I changed ripemd_test.cc like this
> - replace utf-8 quotation mark to escaped ascii double quote : 
>   fprintf(stderr, "Digest incorrect for \"million a's\" test: ");
> 
> - u8 keyword on string literal
>   fprintf(stderr, u8"Digest incorrect for “million a's” test: ");
> 
> both works. but u8 needs c++11 and I didn't test on linux.
> 
> which is better? 
> I will prepare next patch after your reply. 

We already require C++11 to build the tests. Let's try the u8 here and see if any of our consumers complain I suppose. BoringSSL doesn't deal with encodings all that much, but nice to help push minimum toolchains forward.

Beyond that, the non-ASCII characters in comments work out fine, right?

> ps.
> http://api.unrealengine.com/INT/Programming/UnrealArchitecture/StringHandling/CharacterEncoding/index.html#notesaboutc++sourcecodespecifictoeastasianencodings
> 
> it's unreal engine's character encoding document.
> they show if source encoding is utf-8 and compiler recognize source code to default encoding, there can be very strange bugs. (I think it's not problem on boringssl..)
> 
> I think /utf-8 switch is better than surpress C4819, too. 
> but best is remove non-ascii characters from all headers, for library users :)

I think this sort of thing came up previously and we decided to keep the UTF-8. It's 2018. Long past time everyone got with the Unicode thing.

Patch-set: 6