Update patch set 2
Patch Set 2:

>> 2. You might need to move variable declaration at the beginning of a block in following >> files like ssl/t1_lib.c. crypto/bytestring/cbs.c crypto/dsa/dsa_asn1.c crypto/ec/ec_asn1.c crypto/evp/asn1.c crypto/evp/evp_ctx.c ssl/s3_clnt.c ssl/t1_enc.c  ssl/t1_lib.c (*ret = NULL; is still remaining)
> Are you actually getting build failures for these? I can't get gcc/clang to error on this without passing -pendantic, but that causes lots of other, silly errors. I can build with Visual Studio 12 however and it previously failed on t1_lib.c

Yeah, but it could be because I did not apply update2.  Let me check.
e.g. if I do not move DSA_SIG, I see the error like:
...\crypto\dsa\dsa_asn1.c(71) : error C2275: 'DSA_SIG' : illegal use of this types as an expression
C2275 (http://msdn.microsoft.com/en-us/library/76c9k4ah.aspx) sounds strange.

Patch-set: 2