Update patch set 1
Patch Set 1:

I only have this to go on:

$ go version
go version go1.7.1 linux/amd64
$ go build
# _/home/martin/code/boringssl/ssl/test/runner
./key_agreement.go:349: undefined: elliptic.P224

And since no one actually uses P224, and the tests pass without out, I figure, why not.  Up to you.

Patch-set: 1