Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> > Patch Set 6:
> > 
> > > Patch Set 6:
> > > 
> > > Thanks! Which files still need C4819 suppressed? Looking at this documentation, it suggests that, as long as the files are UTF-8 rather than, e.g., Latin-1, we should be fine?
> > > https://msdn.microsoft.com/en-us/library/ms173715.aspx
> > 
> > (I.e. if we have a source file that's encoding a non-ASCII character as something other than UTF-8, fixing it to be UTF-8 sounds good to me.)
> 
> I checked and I don't see any non-UTF-8 files. Even the generated test data file was actually okay, despite the bug in the script. However, I do see this, which implies MSVC uses a byte order mark and otherwise assumes the default code page.
> https://msdn.microsoft.com/en-us/library/mt708821.aspx
> 
> That may be the problem. Chromium appears to indeed pass /utf-8. If you add -utf-8 to lines 163 and 164 in CMakeLists.txt, do you still need to suppress the warning?
> 
> (I'm not sure why the -foo and /foo discrepancy. I'm guessing CMake translates -foo to /foo for MSVC.)

sorry, no latin-1 characters. it's my mistake. 
but there is several utf-8 characters, mostly, comment. 
for examples...
  left double quotation mark (utf-8 : 0xE2 0x80 0x9C)
  right double quotation mark (utf-8 : 0xE2 0x80 0x9D)
  some mathematical symbols like 𝟙, ∀, ², 

before surpress C4819 or /utf-8 switch, even comment occurs warning C4819

surpress C4819 works.
utf-8 swich partially works. there is one error.

error message is here (build using ninja, vs2017)

[1/2] Building CXX object decrepit\CMakeFiles\decrepit_test.dir\ripemd\ripemd_test.cc.obj
FAILED: decrepit/CMakeFiles/decrepit_test.dir/ripemd/ripemd_test.cc.obj 
C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1413~1.261\bin\Hostx64\x64\cl.exe  /nologo /TP -DBORINGSSL_IMPLEMENTATION -DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_STL_EXTRA_DISABLED_WARNINGS="4774 4987" -I..\third_party\googletest\include -I..\decrepit\..\include -utf-8 -Wall -WX  -wd4061 -wd4100 -wd4127 -wd4200 -wd4204 -wd4221 -wd4242 -wd4244 -wd4267 -wd4371 -wd4388 -wd4296 -wd4350 -wd4365 -wd4389 -wd4464 -wd4510 -wd4512 -wd4514 -wd4548 -wd4610 -wd4623 -wd4625 -wd4626 -wd4668 -wd4706 -wd4710 -wd4711 -wd4800 -wd4820 -wd5026 -wd5027  -w44265 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Fodecrepit\CMakeFiles\decrepit_test.dir\ripemd\ripemd_test.cc.obj /Fddecrepit\CMakeFiles\decrepit_test.dir\ /FS -c ..\decrepit\ripemd\ripemd_test.cc
..\decrepit\ripemd\ripemd_test.cc(112): error C2220: warning treated as error - no 'object' file generated
..\decrepit\ripemd\ripemd_test.cc(112): warning C4819: The file contains a character that cannot be represented in the current code page (0). Save the file in Unicode format to prevent data loss
ninja: build stopped: subcommand failed.

ripemd_test.cc(line:112) 
has utf-8 left/right double quotation mark on string literal like below.

  fprintf(stderr, "Digest incorrect for “million a's” test: ");

I changed ripemd_test.cc like this
- replace utf-8 quotation mark to escaped ascii double quote : 
  fprintf(stderr, "Digest incorrect for \"million a's\" test: ");

- u8 keyword on string literal
  fprintf(stderr, u8"Digest incorrect for “million a's” test: ");

both works. but u8 needs c++11 and I didn't test on linux.

which is better? 
I will prepare next patch after your reply. 

ps.
http://api.unrealengine.com/INT/Programming/UnrealArchitecture/StringHandling/CharacterEncoding/index.html#notesaboutc++sourcecodespecifictoeastasianencodings

it's unreal engine's character encoding document.
they show if source encoding is utf-8 and compiler recognize source code to default encoding, there can be very strange bugs. (I think it's not problem on boringssl..)

I think /utf-8 switch is better than surpress C4819, too. 
but best is remove non-ascii characters from all headers, for library users :)

Patch-set: 6
Reviewer: Gerrit User 8880 <8880@66b711a4-aa9b-3dac-9062-916540830212>