Fix name conflict with wincrypt.h in Windows
This fixes the following type of errors
boringssl/include/openssl/base.h:372:29: error: expected ')' before numeric constant
  372 | typedef struct X509_name_st X509_NAME;
      |                             ^~~~~~~~~

Change-Id: I14d3186efe5b54d058277bc4be5125239958f65e