Update patch set 1
Patch Set 1: Code-Review+2 Commit-Queue+2

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > > Patch Set 1: Commit-Queue+1
> > > > 
> > > > Hrm. I'm confused why we haven't hit this ourselves. Just to make sure I follow, is the scenario that you pass --target in CMAKE_CXX_FLAGS yourself when building, or is this somehow happening automatically?
> > > 
> > > Yes, this is specifically if you pass --target into CMAKE_CXX_FLAGS.
> > > 
> > > I'm running into this because the Rust tooling does this by default. https://github.com/alexcrichton/cmake-rs/issues/38 has some context from their side, too.
> > > 
> > > If --target=x86_64-apple-darwin and without this patch, you get the utterly useless error that std::unique_ptr doesn't exist.
> > > 
> > > If --target=x86_64-apple-darwin and with this patch, you get a more useful error telling you that you need to target at least darwin11.
> > > 
> > > If --target=x86_64-apple-darwin11 or greater and with this patch, everything works fine.
> > 
> > Sorry about the delay. I've actually been on vacation the past week and only just got back.
> > 
> > So I toyed with clang++ on my Mac and wasn't able to reproduce this. I also tried toying with a standalone file (just a #include <memory> with a std::unique_ptr usage) and that also didn't repro. I got some really weird stuff actually:
> > 
> > --target=zzzz: Compiler complains about unknown triple
> > --target=x86_64-zzzz: Compile accepts the triple, but then #include <memory> fails. No amount of -std=c++11 or -stdlib=libc++ seems to appease it.
> > --target=x86_64-apple-zzzz: Ditto
> > --target=x86_64-apple-darwin: Works just fine with or without -stdlib=libc++
> > --target=x86_64-apple-darwin11: Also works just fine with or without -stdlib=libc++
> > --target=x86_64-apple-darwinzzzz: ALSO works just fine with or without -stdlib=libc++!
> > 
> > I'm not entirely sure what that flag is intended to do here. :-)
> 
> Intriguing! Are you using Apple's clang++ or a self-built one? I'm using Apple's one, and here's my toying:
> 
> $ clang++ --version
> Apple LLVM version 9.0.0 (clang-900.0.38)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> 
> $ cat c11.cc
> #include <memory>
> 
> int main(void) {
>   std::unique_ptr<int> p;
>   return 0;
> }
> 
> $ clang++ c11.cc --target=x86_64-apple-darwin
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
> c11.cc:4:8: error: no member named 'unique_ptr' in namespace 'std'
>   std::unique_ptr<int> p;
>   ~~~~~^
> c11.cc:4:22: error: expected '(' for function-style cast or type construction
>   std::unique_ptr<int> p;
>                   ~~~^
> c11.cc:4:24: error: use of undeclared identifier 'p'
>   std::unique_ptr<int> p;
>                        ^
> 3 errors generated.
> 
> $ clang++ c11.cc --target=x86_64-apple-darwin11
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
> c11.cc:4:8: error: no member named 'unique_ptr' in namespace 'std'
>   std::unique_ptr<int> p;
>   ~~~~~^
> c11.cc:4:22: error: expected '(' for function-style cast or type construction
>   std::unique_ptr<int> p;
>                   ~~~^
> c11.cc:4:24: error: use of undeclared identifier 'p'
>   std::unique_ptr<int> p;
>                        ^
> 3 errors generated.
> 
> $ clang++ c11.cc --target=x86_64-apple-darwin -stdlib=libc++
> clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
> 
> $ clang++ c11.cc --target=x86_64-apple-darwin11 -stdlib=libc++ && echo success
> success

Yup, that's exactly what I'm doing, even down to std::unique_ptr<int>:

$ cat foo.cc
#include <memory>
int main() { std::unique_ptr<int> i; (void)i; }

$ clang++ --version
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode 9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ clang++ foo.cc --target=x86_64-apple-darwin11 && echo Success
Success

It looks like my clang is just a hair older than yours, but otherwise the same? I can see if I can figure out how to update it. (I don't entirely understand Apple's toolchain setup.)

One thing I do notice though is that, if I pass -stdlib=libstdc++, then I get the same errors as you, down to the deprecation warning. Perhaps, despite my having the slightly older clang, something else about my setup is *newer* and causing libstdc++ to get picked up! Maybe something about SDK versions?

Anyway, since I can certainly reproduce that libstdc++ is completely unsuitable for BoringSSL, your patch can only be, at worst, a no-op. It's probably not worth the time to figure out exactly what's causing your libstdc++ default beyond that.

Patch-set: 1
Reviewer: Gerrit User 5415 <5415@66b711a4-aa9b-3dac-9062-916540830212>
Label: Code-Review=+2
Label: Commit-Queue=+2