Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > > Patch Set 1:
> > > > 
> > > > The warning should not be triggering in this case, right? And it's not just that the compiler cannot know that it shouldn't be triggering, it's that the compiler is just being dumb, I think.
> > > > 
> > > > If so, dropping the warning for this compiler version in CMake seems like the best answer.
> > > 
> > > The compiler might be getting upset that we're incrementing p224_limb points across a p224_felem boundary. The pointer cast is probably just serving to confuse it. :-/
> > > 
> > > Although, in that case, I'm a little puzzled why inlimbs isn't also making it explode. What's the exact warning? If you replace the memset with out rather than outlimbs and then the loop with two nested loops of out[0..3][0..2], does that appease it?
> > 
> > Yeah, it's definitely an unsatisfactory patch; I guess turning off the compiler warning is probably reasonable. Would turning it off for gcc as a whole be acceptable?
> > 
> > The exact error messages are:
> > 
> > /boringssl/crypto/fipsmodule/ec/p256-64.c:1412:31: error: array subscript is above array bounds [-Werror=array-bounds]
> > 
> > /boringssl/crypto/fipsmodule/ec/p224-64.c:882:32: error: array subscript is above array bounds [-Werror=array-bounds]
> > 
> > It's specifically complaining about the calculation of out, rather than the use of it.
> > 
> > (Accordingly, changing the memset has no effect).
> 
> Oh, right, I'll try rewriting the whole loop to get rid of {in,out}limbs completely.

Oh, yuck. Okay, if it's complaining about the calculation of out, then I agree with Adam. The compiler is just confused. Turning it off for the just the affected versions is probably better? I've never seen this on GCC 4.8.4, so it's maybe just a 4.7 thing? I'll see if I can find a reference to a bug anywhere.

(I'd have to go trawling through the C spec to see whether hopping across multi-dimensional arrays is technically allowed or not, but it sounds like that's not what the compiler was complaining about anyway?)

Patch-set: 1
Reviewer: Gerrit User 5415 <5415@66b711a4-aa9b-3dac-9062-916540830212>