Update patch set 3
Patch Set 3:

> Lgtm, thanks! What does it warn about? If you need this for win
 > headers, warnings might be too strict imho. (Clang-cl never warns
 > about system headers by default, not sure why msvs2013 thinks
 > warning on system headers is useful)

I think the problem is we use /Wall with a blacklist instead of /W4 and Microsoft doesn't promise their headers are clean enough for that. I dunno. There are some valuable warnings in there I think, but it is certainly a bit of a hassle. :-/

It complains about:

E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64\cl.exe   /nologo -DBORINGSSL_IMPLEMENTATION -DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -I..\crypto\..\include -Wall -WX  -wd4100 -wd4127 -wd4200 -wd4242 -wd4244 -wd4245 -wd4267 -wd4371 -wd4388 -wd4296 -wd4350 -wd4365 -wd4389 -wd4464 -wd4510 -wd4512 -wd4514 -wd4548 -wd4610 -wd4623 -wd4625 -wd4626 -wd4706 -wd4710 -wd4711 -wd4800 -wd4820 -wd5027  -w44265 /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Focrypto\CMakeFiles\crypto.dir\mem.c.obj /Fdcrypto\CMakeFiles\crypto.dir\ /FS -c ..\crypto\mem.c
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\smmintrin.h(82): error C2220: warning treated as error - no 'object' file generated
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\smmintrin.h(82): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\nmmintrin.h(35): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\wmmintrin.h(34): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\immintrin.h(1305): warning C4255: '_readfsbase_u32': no function prototype given: converting '()' to '(void)'
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\immintrin.h(1306): warning C4255: '_readgsbase_u32': no function prototype given: converting '()' to '(void)'
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\immintrin.h(1307): warning C4255: '_readfsbase_u64': no function prototype given: converting '()' to '(void)'
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\immintrin.h(1308): warning C4255: '_readgsbase_u64': no function prototype given: converting '()' to '(void)'
E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\include\ammintrin.h(251): warning C4255: '__slwpcb': no function prototype given: converting '()' to '(void)'

Patch-set: 3