Update patch set 3
Change has been successfully cherry-picked as 7198d1132bc194b360c37b05b9a82f6231533114

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: ssl/encrypted_client_hello.cc
Insertions: 2, Deletions: 2.

@@ -206,7 +206,7 @@
       // The ECH extension itself is not in the AAD and may not be referenced.
       if (want == TLSEXT_TYPE_encrypted_client_hello) {
         *out_alert = SSL_AD_ILLEGAL_PARAMETER;
-        OPENSSL_PUT_ERROR(SSL, SSL_R_OUTER_EXTENSION_NOT_FOUND);
+        OPENSSL_PUT_ERROR(SSL, SSL_R_INVALID_OUTER_EXTENSION);
         return false;
       }
       // Seek to |want| in |outer_extensions|. |ext_list| is required to match
@@ -216,7 +216,7 @@
       do {
         if (CBS_len(&outer_extensions) == 0) {
           *out_alert = SSL_AD_ILLEGAL_PARAMETER;
-          OPENSSL_PUT_ERROR(SSL, SSL_R_OUTER_EXTENSION_NOT_FOUND);
+          OPENSSL_PUT_ERROR(SSL, SSL_R_INVALID_OUTER_EXTENSION);
           return false;
         }
         if (!CBS_get_u16(&outer_extensions, &found) ||
```
```
The name of the file: ssl/test/runner/runner.go
Insertions: 4, Deletions: 8.

@@ -16776,9 +16776,7 @@
 				},
 				shouldFail:         true,
 				expectedLocalError: "remote error: illegal parameter",
-				// The decoding algorithm relies on the ordering requirement, so
-				// the wrong order appears as a missing extension.
-				expectedError: ":OUTER_EXTENSION_NOT_FOUND:",
+				expectedError:      ":INVALID_OUTER_EXTENSION:",
 			})
 
 			// Test that the server rejects duplicated values in ech_outer_extensions.
@@ -16812,9 +16810,7 @@
 				},
 				shouldFail:         true,
 				expectedLocalError: "remote error: illegal parameter",
-				// The decoding algorithm relies on the ordering requirement, so
-				// duplicates appear as missing extensions.
-				expectedError: ":OUTER_EXTENSION_NOT_FOUND:",
+				expectedError:      ":INVALID_OUTER_EXTENSION:",
 			})
 
 			// Test that the server rejects references to missing extensions in
@@ -16843,7 +16839,7 @@
 				},
 				shouldFail:         true,
 				expectedLocalError: "remote error: illegal parameter",
-				expectedError:      ":OUTER_EXTENSION_NOT_FOUND:",
+				expectedError:      ":INVALID_OUTER_EXTENSION:",
 			})
 
 			// Test that the server rejects a references to the ECH extension in
@@ -16871,7 +16867,7 @@
 				},
 				shouldFail:         true,
 				expectedLocalError: "remote error: illegal parameter",
-				expectedError:      ":OUTER_EXTENSION_NOT_FOUND:",
+				expectedError:      ":INVALID_OUTER_EXTENSION:",
 			})
 		}
 
```
```
The name of the file: crypto/err/ssl.errordata
Insertions: 1, Deletions: 1.

@@ -90,6 +90,7 @@
 SSL,318,INVALID_ECH_CONFIG_LIST
 SSL,317,INVALID_ECH_PUBLIC_NAME
 SSL,159,INVALID_MESSAGE
+SSL,320,INVALID_OUTER_EXTENSION
 SSL,251,INVALID_OUTER_RECORD_TYPE
 SSL,269,INVALID_SCT_LIST
 SSL,295,INVALID_SIGNATURE_ALGORITHM
@@ -133,7 +134,6 @@
 SSL,187,OLD_SESSION_CIPHER_NOT_RETURNED
 SSL,268,OLD_SESSION_PRF_HASH_MISMATCH
 SSL,188,OLD_SESSION_VERSION_NOT_RETURNED
-SSL,320,OUTER_EXTENSION_NOT_FOUND
 SSL,189,OUTPUT_ALIASES_INPUT
 SSL,190,PARSE_TLSEXT
 SSL,191,PATH_TOO_LONG
```
```
The name of the file: include/openssl/ssl.h
Insertions: 1, Deletions: 1.

@@ -5598,7 +5598,7 @@
 #define SSL_R_INVALID_ECH_PUBLIC_NAME 317
 #define SSL_R_INVALID_ECH_CONFIG_LIST 318
 #define SSL_R_ECH_REJECTED 319
-#define SSL_R_OUTER_EXTENSION_NOT_FOUND 320
+#define SSL_R_INVALID_OUTER_EXTENSION 320
 #define SSL_R_INCONSISTENT_ECH_NEGOTIATION 321
 #define SSL_R_SSLV3_ALERT_CLOSE_NOTIFY 1000
 #define SSL_R_SSLV3_ALERT_UNEXPECTED_MESSAGE 1010
```


Patch-set: 3
Subject: Explicitly reject self-referential ech_outer_extensions.
Status: merged
Commit: 7198d1132bc194b360c37b05b9a82f6231533114
Tag: autogenerated:gerrit:merged
Groups: 3aae6da39baae09d6b6e000d2f32e6e0bec6ae69
Label: Code-Review=+2, 42c8be8763561c1990957202283524df67106479 Gerrit User 5005 <5005@66b711a4-aa9b-3dac-9062-916540830212>
Label: Commit-Queue=+2, 67955aca0ddfc0ab928863cb0dcbea8b06838a9f Gerrit User 5415 <5415@66b711a4-aa9b-3dac-9062-916540830212>
Label: SUBM=+1, 1bc09cf1b971eba0ced27e419e19e247963260c2
Submission-id: 51185
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~PrologRule
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Commit-Queue
Submitted-with: OK: Code-Review: Gerrit User 5005 <5005@66b711a4-aa9b-3dac-9062-916540830212>
Submitted-with: MAY: Bot-Commit
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners