Update patch set 3
Patch Set 3:

> Change has been successfully cherry-picked as 33970e6ce0de1a553bd57d5b42527cd95292acae by Adam Langley

Old issue, new comment. But this breaks in MinGW:

f:/MingW32/TDM-gcc/x86_64-w64-mingw32/include/limits.h:20:0: note: this is the location of the previous definition
 #define PATH_MAX 260
 ^
tool/digest.cc:40:13: error: conflicting declaration 'typedef int ssize_t'
 typedef int ssize_t;
             ^
In file included from f:/MingW32/TDM-gcc/x86_64-w64-mingw32/include/stdio.h:9:0,
                 from ././tmp64/missing.h:67,
                 from <command-line>:0:
f:/MingW32/TDM-gcc/x86_64-w64-mingw32/include/crtdefs.h:45:35: note: previous declaration as 'typedef long long int ssize_t'
 __MINGW_EXTENSION typedef __int64 ssize_t;
                                   ^

Patch-set: 3
CC: Gerrit User 5480 <5480@66b711a4-aa9b-3dac-9062-916540830212>