Update patch set 3
Patch Set 3:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 31725: Change 31725 is work in progress

Patch-set: 3
Tag: autogenerated:cq:full-run
Reviewer: Gerrit User 6985 <6985@66b711a4-aa9b-3dac-9062-916540830212>